CREATE TABLE [dbo].[AppUpdate]
(
	[Id] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL PRIMARY KEY,
	[VersionName] NVARCHAR(32) NOT NULL,
	[VersionCode] INT NOT NULL UNIQUE,
	[FileName] NVARCHAR(255) NOT NULL,
	[ZipFile] VARBINARY(MAX) FILESTREAM,
)
