CREATE TABLE [dbo].[AppUpdates]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Version] NVARCHAR(256) NOT NULL,
	[FileName] NVARCHAR(256) NOT NULL,
	[Checksum] NVARCHAR(256) NOT NULL,
	[ReleaseDate] DATETIME NOT NULL,
	[FileData] VARBINARY(MAX) NOT NULL
)
