CREATE TABLE [dbo].[UpdateInfo]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Version] NVARCHAR(256) NOT NULL,
	[FileName] NVARCHAR(256) NOT NULL,
	[FileDir] NVARCHAR(256) NULL,
	[CheckSum] NVARCHAR(256) NOT NULL,
	[ReleaseDate] DATETIME NOT NULL,
)
